force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Added as Primary on</relationshipLabel>
    <relationshipName>AccountsLinkedPrimary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Timestamp__c</fullName>
    <label>Primary Contact Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler {
  
  public static Set<Id> processedAccountIds = new Set<Id>();
  
  public static void beforeInsert(List<Account> newAccountsList){
    //AccountTriggerHelper.customAccountValidations(newAccountsList, null);
  }
  
  public static void beforeUpdate(List<Account> newAccountsList, Map<Id, Account> oldAccountsMap){
    //AccountTriggerHelper.customAccountValidations(newAccountsList, oldAccountsMap);
  }
  
  public static void afterUpdate(List<Account> newAccountsList, Map<Id, Account> oldAccountsMap){
    Map<Account, Id> newAccountsListFilteredMappedPC = new Map<Account, Id>();
    for(Account acc : newAccountsList){
      if(processedAccountIds.contains(acc.Id)){ //added on purpose to block recursion
        continue;
      }
      if(
        (acc.Primary_Contact__c != null && acc.Primary_Contact__c != oldAccountsMap.get(acc.Id).Primary_Contact__c)
        || (acc.Primary_Contact_Timestamp__c != oldAccountsMap.get(acc.Id).Primary_Contact_Timestamp__c)
      ){
        System.debug('AccountTimestamps   ' +oldAccountsMap.get(acc.Id).Primary_Contact_Timestamp__c + ' ' + acc.Primary_Contact_Timestamp__c);
        newAccountsListFilteredMappedPC.put(acc, acc.Primary_Contact__c);
      }
    }
    if(!newAccountsListFilteredMappedPC.isEmpty()){
      AccountTriggerHelper.updateMadePrimaryDateOnContact(newAccountsListFilteredMappedPC);
    }
  }
}